AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-add2

  Sample SAM Template for sam-add2

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
Resources:
  FactorialFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: controllers/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Factorial:
          Type: Api
          Properties:
            Path: /factorial/{number}
            Method: get

  ModuleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: controllers/
      Handler: module_function.module_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Module:
          Type: Api
          Properties:
            Path: /module
            Method: get

Outputs:
  FactorialApi:
    Description: API Gateway endpoint URL for Prod stage for Factorial function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/factorial/"

  ModuleApi:
    Description: API Gateway endpoint URL for Prod stage for Module function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/module/"

  FactorialFunction:
    Description: Factorial Lambda Function ARN
    Value: !GetAtt FactorialFunction.Arn

  ModuleFunction:
    Description: Module Lambda Function ARN
    Value: !GetAtt ModuleFunction.Arn

  FactorialFunctionIamRole:
    Description: Implicit IAM Role created for Factorial function
    Value: !GetAtt FactorialFunctionRole.Arn

  ModuleFunctionIamRole:
    Description: Implicit IAM Role created for Module function
    Value: !GetAtt ModuleFunctionRole.Arn
